---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monerod-config
  namespace: monerometrics
data:
  monerod.conf: |
    data-dir=/data
    prune-blockchain=1
    rpc-bind-ip=0.0.0.0
    rpc-bind-port=18081
    confirm-external-bind=1
    restricted-rpc=1
    p2p-bind-ip=0.0.0.0
    p2p-bind-port=18080
    no-igd=1
    no-zmq=1
    log-level=0
    log-file=/data/monerod.log
    max-log-file-size=104857600
    max-log-files=3
    fast-block-sync=1
    max-concurrency=4
    db-sync-mode=fast:async:250000000bytes
    sync-pruned-blocks=1
    block-sync-size=100
    out-peers=32
