---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monerod-data
  namespace: monerometrics
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 90Gi
  storageClassName: local-path
