---
galaxy_info:
  role_name: data_disk
  author: noe
  description: Format and mount Azure data disk for applicative data
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
