---
# Inventaire Ansible POC monerometrics
# Utilise les alias SSH definis dans ~/.ssh/config

all:
  children:
    bastion:
      hosts:
        bastion-poc:
          ansible_host: monero-bastion
          ansible_user: noe
          ansible_python_interpreter: /usr/bin/python3

    edge:
      hosts:
        edge-poc:
          ansible_host: monero-edge
          ansible_user: noe
          ansible_python_interpreter: /usr/bin/python3
