---
galaxy_info:
  role_name: nginx
  author: noe
  description: Install and configure nginx reverse proxy on Ubuntu 24.04
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
