---
galaxy_info:
  role_name: tailscale
  author: noe
  description: Install Tailscale and join tailnet on Ubuntu 24.04
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
